name: "Clean artifacts after PR have been merged"
on:
  pull_request:
    types:
      - closed

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if artifact is presented
        id: presented
        continue-on-error: true
        run: |
           echo "ARTIFACT_ID=$(curl -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -e -r '.artifacts[] | select(.name=="${{ github.event.number }}-unlabeled-status")|.id')" >> $GITHUB_ENV 
      - name:
        if: steps.presented.outcome == 'success'
        run: |
          echo "${{ env.ARTIFACT_ID }}"
          curl -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -X DELETE \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.ARTIFACT_ID }}
