name: "Dismiss approvals for DB changes"
on: [pull_request]

jobs:
  dismiss-approval-if-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
      - name: Check for DB changes
        id: contains_db_change
        continue-on-error: true
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            if [[ ( $file =~ .*\/build\.gradle.* || $file =~ .*\/db\/changelog\/.* || $file =~ .*\/db.*changelog.*/ ) && ! $file =~ .*\/test\/.* ]]; then
              exit 0
            fi
          done
          exit 1
      - name: Get PR number
        id: pr_number
        uses: actions/github-script@v3
        with:
          script: |
            const pull_request = context.payload.pull_request
            return pull_request.number
      - name: Get and dismiss PR reviews
        if: steps.contains_db_change.outcome == 'success'
        run: |
          echo "Dismissing approvals because DB changes are found"
          reviews=$(gh api --method GET \
            -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ steps.pr_number.outputs.result }}/reviews)
          echo $reviews
          review_ids=$(echo $reviews | jq '.[] | select(.state=="APPROVED") | .id' )
          for review_id in $review_ids; do
            echo "Dismissing review $review_id"
            echo "Sending request to: /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ steps.pr_number.outputs.result }}/reviews/${review_id}/dismissals"
            gh api --method PUT \
              -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ steps.pr_number.outputs.result }}/reviews/${review_id}/dismissals \
              -f message='Dismissing approvals due to DB file changes' \
              -f event='DISMISS'
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
