name: "risky-pr-labeler using Labeler"
on: [ pull_request ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if already was labeled
        id: was_unlabeled
        continue-on-error: true
        run: |
           curl -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -e -r '.artifacts[] | select(.name=="${{ github.event.number }}-unlabeled-status")|.id'
      # https://github.com/marketplace/actions/pr-labeler-based-on-multiple-rules
      - uses: srvaroa/labeler@v0.8
        if: steps.was_unlabeled.outcome == 'failure'
        with:
          config_path: .github/labeler_config.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
